package util

val IND_PRETERITE_PRESENT_DUERFEN = "darf"

val IND_PRETERITE_PRESENT_KOENNEN = "kann"

val IND_PRETERITE_PRESENT_MOECHTE = "möchte"

val IND_PRETERITE_PRESENT_MOEGEN = "mag"

val IND_PRETERITE_PRESENT_MUESSEN = "muss"

val IND_PRETERITE_PRESENT_SOLLEN = "soll"

val IND_PRETERITE_PRESENT_WISSEN = "weiß"

val IND_PRETERITE_PRESENT_WOLLEN = "will"
